/*
=====================================
Gezinsplanner
Bestand : core.js
Versie  : v1.37.0
Laatst gewijzigd : 06-08-2026

Functie :
- Opslaan van gegevens
- LocalStorage
- Algemene functies

Wijzigingen:
- Code opgesplitst
- Backup-opslag toegevoegd
=====================================
*/

const defaultCategories = [
  "Bakproducten",
  "Broodbeleg (zoet)",
  "Broodbeleg (hartig)",
  "Brood & ontbijtproducten",
  "Diepvries",
  "Dranken",
  "Fruit",
  "Groente",
  "Kruiden",
  "Olie / saus",
  "Zuivel",
  "Bewaarproducten (voorraad)",
  "Snacks & tussendoor",
  "Schoonmaak & huishouden",
  "Huisdier",
  "Persoonlijke verzorging",
  "Keukenbenodigdheden",
  "Overig",
];
const stockCatalog = [
  {
    id: 1000,
    name: "Bakpoeder",
    category: "Bakproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1001,
    name: "(GV) bloem",
    category: "Bakproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1002,
    name: "Droge gist",
    category: "Bakproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1003,
    name: "Suiker",
    category: "Bakproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1004,
    name: "Vanillesuiker",
    category: "Bakproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1005,
    name: "Appelstroop",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1006,
    name: "Hagelslag",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1007,
    name: "Jam aardbeien",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1008,
    name: "(GV) pindakaas",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1009,
    name: "Pindakaas",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1010,
    name: "Speculoos",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1011,
    name: "Vlokken",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1012,
    name: "Vruchtenhagel",
    category: "Broodbeleg (zoet)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1013,
    name: "Boterhamworst",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1014,
    name: "Gelderse worst",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1015,
    name: "Grillworst",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1016,
    name: "(GV) humus",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1017,
    name: "Leverpastei",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1018,
    name: "Palingworst",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1019,
    name: "(GV) roomkaas",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1020,
    name: "Salami",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1021,
    name: "(GV) smeerkaas",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1022,
    name: "Smeerkaas",
    category: "Broodbeleg (hartig)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1023,
    name: "Brinta",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1024,
    name: "(GV) broodjes",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1025,
    name: "Chocopops",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1026,
    name: "Cruesli",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1027,
    name: "(GV) granola",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1028,
    name: "(GV) havermout",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1029,
    name: "Honey rings",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1030,
    name: "(GV) knackebrod",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1031,
    name: "Knackebrod",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1032,
    name: "(GV) maiswafels",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1033,
    name: "Muesli",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1034,
    name: "(GV) pitabroodjes",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1035,
    name: "(GV) wraps",
    category: "Brood & ontbijtproducten",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1036,
    name: "Gedroogd/diepvries fruit",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1037,
    name: "Roerbakmix",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1038,
    name: "Soepgroente",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1039,
    name: "Bitterballen",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1040,
    name: "Friet",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1041,
    name: "Frikandellen",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1042,
    name: "Kroketten",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1043,
    name: "(GV) snacks",
    category: "Diepvries",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1044,
    name: "Appelsap",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1045,
    name: "Cola",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1046,
    name: "Fanta lemon",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1047,
    name: "Ice tea sparkling",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1048,
    name: "Karvan Cevitam Aardbei",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1049,
    name: "Karvan Cevitam Framboos",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1050,
    name: "Karvan Cevitam Grenadine",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1051,
    name: "Koffiebonen",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1052,
    name: "Sinas",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1053,
    name: "Thee green",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1054,
    name: "Thee aardbeien",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1055,
    name: "Thee munt",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1056,
    name: "Thee zwart",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1057,
    name: "Wijn rood",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1058,
    name: "Wijn rosé",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1059,
    name: "Wijn wit",
    category: "Dranken",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1060,
    name: "Appels",
    category: "Fruit",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1061,
    name: "Bananen",
    category: "Fruit",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1062,
    name: "Druiven",
    category: "Fruit",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1063,
    name: "Fruit gemengd",
    category: "Fruit",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1064,
    name: "Kiwi",
    category: "Fruit",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1065,
    name: "Gemengde sla",
    category: "Groente",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1066,
    name: "Paprika",
    category: "Groente",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1067,
    name: "Bami- of nasikruiden",
    category: "Kruiden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1068,
    name: "Basilicum",
    category: "Kruiden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1069,
    name: "Italiaanse kruidenmix",
    category: "Kruiden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1070,
    name: "Kaneel",
    category: "Kruiden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1071,
    name: "Knoflookpoeder",
    category: "Kruiden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1072,
    name: "Tex-mex kruidenmix",
    category: "Kruiden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1073,
    name: "Uienpoeder",
    category: "Kruiden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1074,
    name: "Azijn",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1075,
    name: "Curry",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1076,
    name: "Frietsaus",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1077,
    name: "Ketjap",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1078,
    name: "Mayonaise",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1079,
    name: "Olijfolie extra vergine",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1080,
    name: "Sojasaus",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1081,
    name: "Zonnebloemolie",
    category: "Olie / saus",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1082,
    name: "Eieren",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1083,
    name: "Halfvolle melk 2 liter",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1084,
    name: "Halfvolle melk 1 liter",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1085,
    name: "(GV) halvarine groen",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1086,
    name: "Halvarine blauw",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1087,
    name: "Jong belegen kaas",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1088,
    name: "Yoghurt / kwark",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1089,
    name: "Yoghurtdrink",
    category: "Zuivel",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1090,
    name: "Augurk",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1091,
    name: "Bouillonblokjes groente",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1092,
    name: "Bouillonblokjes kip",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1093,
    name: "Bouillonblokjes rund",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1094,
    name: "Bouillonblokjes vis",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1095,
    name: "Currypasta",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1096,
    name: "Frituurolie",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1097,
    name: "Suikerklontjes",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1098,
    name: "Tonijn op water",
    category: "Bewaarproducten (voorraad)",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1099,
    name: "Snoepjes",
    category: "Snacks & tussendoor",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1100,
    name: "Tussendoortjes",
    category: "Snacks & tussendoor",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1101,
    name: "Afwasmiddel",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1102,
    name: "Allesreiniger",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1103,
    name: "Bleek",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1104,
    name: "GFT-zakken",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1105,
    name: "Glansspoelmiddel",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1106,
    name: "Handzeep",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1107,
    name: "Wc-papier",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1108,
    name: "Pedaalemmerzakken",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1109,
    name: "PMD-zakken",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1110,
    name: "Schuursponsjes",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1111,
    name: "Stofzuigerzakken",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1112,
    name: "Vaatwastabletten",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1113,
    name: "Vaatwaszout",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1114,
    name: "Vuilniszakken",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1115,
    name: "Waspoeder",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1116,
    name: "Wasverzachter",
    category: "Schoonmaak & huishouden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1117,
    name: "Kattenbakvulling",
    category: "Huisdier",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1118,
    name: "Kattenbrokjes",
    category: "Huisdier",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1119,
    name: "Kattensnoepjes",
    category: "Huisdier",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1120,
    name: "Natvoer",
    category: "Huisdier",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1121,
    name: "Conditioner",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1122,
    name: "Deodorant",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1123,
    name: "Douchegel",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1124,
    name: "Excedrin",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1125,
    name: "Inlegkruisjes",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1126,
    name: "Maandverband/tampons",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1127,
    name: "Paracetamol",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1128,
    name: "Pleisters",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1129,
    name: "Scheerproducten",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1130,
    name: "Shampoo",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1131,
    name: "Tandpasta",
    category: "Persoonlijke verzorging",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1132,
    name: "Aluminiumfolie",
    category: "Keukenbenodigdheden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1133,
    name: "Bakpapier",
    category: "Keukenbenodigdheden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1134,
    name: "Boterhamzakjes",
    category: "Keukenbenodigdheden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1135,
    name: "Diepvrieszakjes",
    category: "Keukenbenodigdheden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1136,
    name: "Extra plastic bakjes",
    category: "Keukenbenodigdheden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
  {
    id: 1137,
    name: "Vershoudfolie",
    category: "Keukenbenodigdheden",
    packageType: "",
    packageContent: "",
    unit: "",
    currentAmount: "",
    minimum: "",
    toHutsel: false,
    buyCount: "",
    amount: "",
  },
];
const defaultRecipes = [
  {
    id: 9001,
    name: "Zomerse Spaghetti-salade",
    portions: 4,
    method:
      "Breek de spaghetti in kleine stukjes. Kook deze in ruim water met het bouillontablet in circa 10 minuten gaar. Giet af, spoel koud en laat afkoelen. Laat de vruchten uitlekken. Snijd ham, kaas en paprika in stukjes. Schil de appels, snijd ze in kleine partjes en besprenkel met citroensap. Houd wat vruchten en paprika apart. Meng de overige ingrediënten door de spaghetti. Maak een saus van mayonaise en koffieroom en voeg bieslook, peterselie en worcestershiresaus naar smaak toe. Meng door de salade en garneer met de achtergehouden vruchten en paprika.",
    ingredients: [
      { name: "Spaghetti", amount: 300, unit: "gram", stockId: null },
      { name: "Bouillontablet", amount: 1, unit: "stuks", stockId: null },
      { name: "Gemengde vruchten", amount: 1, unit: "blik", stockId: null },
      { name: "Gekookte ham", amount: 150, unit: "gram", stockId: null },
      { name: "Jong belegen kaas", amount: 300, unit: "gram", stockId: null },
      { name: "Rode paprika", amount: 1, unit: "stuks", stockId: null },
      { name: "Appels", amount: 2, unit: "stuks", stockId: null },
      { name: "Citroensap", amount: "", unit: "naar smaak", stockId: null },
      { name: "Mayonaise", amount: 2, unit: "eetlepel", stockId: null },
      { name: "Koffieroom", amount: "", unit: "naar smaak", stockId: null },
      { name: "Bieslook", amount: "", unit: "naar smaak", stockId: null },
      { name: "Peterselie", amount: "", unit: "naar smaak", stockId: null },
      {
        name: "Worcestershiresaus",
        amount: "",
        unit: "naar smaak",
        stockId: null,
      },
    ],
  },
  {
    id: 9002,
    name: "Glutenvrije Worcestershiresaus",
    portions: 1,
    method:
      "Doe alle ingrediënten in een steelpan. Breng aan de kook en roer goed door. Laat 10 minuten zachtjes pruttelen met het deksel erop. Verwijder het laurierblad. Mix eventueel glad met een staafmixer. Laat afkoelen en giet in een schone fles. In de koelkast tot 2 maanden houdbaar.",
    ingredients: [
      { name: "Appelciderazijn", amount: 250, unit: "ml", stockId: null },
      { name: "Water", amount: 60, unit: "ml", stockId: null },
      {
        name: "Tamari of glutenvrije sojasaus",
        amount: 2,
        unit: "eetlepel",
        stockId: null,
      },
      { name: "Citroensap", amount: 2, unit: "eetlepel", stockId: null },
      {
        name: "Melasse of donkere basterdsuiker",
        amount: 2,
        unit: "eetlepel",
        stockId: null,
      },
      { name: "Vissaus", amount: 1, unit: "eetlepel", stockId: null },
      { name: "Uienpoeder", amount: 1, unit: "theelepel", stockId: null },
      { name: "Knoflookpoeder", amount: 1, unit: "theelepel", stockId: null },
      { name: "Gemberpoeder", amount: 0.5, unit: "theelepel", stockId: null },
      { name: "Kaneel", amount: 0.25, unit: "theelepel", stockId: null },
      {
        name: "Gemalen kruidnagel",
        amount: 0.25,
        unit: "theelepel",
        stockId: null,
      },
      { name: "Zwarte peper", amount: 0.25, unit: "theelepel", stockId: null },
      { name: "Ansjovisfilet", amount: 1, unit: "stuks", stockId: null },
      { name: "Laurierblad", amount: 1, unit: "stuks", stockId: null },
    ],
  },
  {
    id: 9003,
    name: "Spaghetti bolognese",
    portions: 8,
    method:
      "1. Verhit 4 eetlepels olijfolie in een ruime braadpan. Bak het gehakt 6–8 minuten bruin op hoog vuur. Voeg de rozemarijn toe en bak nog 5 minuten.\n\n2. Snijd de bleekselderij, winterpenen en uien fijn. Voeg ze toe en bak ongeveer 5 minuten mee.\n\n3. Voeg de tomatenpuree toe en bak 1 minuut mee. Schenk de rode wijn erbij. Maak 1 liter runderbouillon en voeg deze toe.\n\n4. Laat de saus 1½ tot 2 uur zachtjes sudderen tot hij mooi is ingedikt. Breng op smaak met zwarte peper en zout.\n\n5. Kook de spaghetti volgens de aanwijzingen op de verpakking.\n\n6. Meng de spaghetti met de saus en rasp er Grana Padano over.\n\nTip: lekker met verse basilicum. Maak eventueel extra saus en vries deze in porties in.",
    ingredients: [
      { name: "Gemengd gehakt", amount: 1000, unit: "gram", stockId: null },
      { name: "Winterpenen", amount: 2, unit: "stuks", stockId: null },
      { name: "Bleekselderij", amount: 4, unit: "stuks", stockId: null },
      { name: "Rozemarijn", amount: 4, unit: "stuks", stockId: null },
      { name: "Tomatenpuree", amount: 2, unit: "eetlepel", stockId: null },
      { name: "Spaghetti", amount: 600, unit: "gram", stockId: null },
      { name: "Grana Padano", amount: "", unit: "naar smaak", stockId: null },
      { name: "Uien", amount: 2, unit: "stuks", stockId: null },
      { name: "Rode wijn", amount: 200, unit: "ml", stockId: null },
      { name: "Runderbouillon", amount: 1000, unit: "ml", stockId: null },
      { name: "Zwarte peper", amount: "", unit: "naar smaak", stockId: null },
      { name: "Zout", amount: "", unit: "naar smaak", stockId: null },
      { name: "Olijfolie", amount: 4, unit: "eetlepel", stockId: null },
    ],
  },
];
const seed = {
  recipes: defaultRecipes.map((r) => JSON.parse(JSON.stringify(r))),
  shopping: [],
  meals: [
    {
      id: 11,
      day: "Woensdag",
      letter: "A",
      name: "Kip, krieltjes, spinazie en rodekool",
      note: "Thuiskommaaltijd",
    },
    {
      id: 12,
      day: "Donderdag",
      letter: "B",
      name: "Spaghetti bolognese",
      note: "Slowcooker, extra voor vriezer",
    },
    {
      id: 13,
      day: "Vrijdag",
      letter: "C",
      name: "Vrije keuze / barbecue",
      note: "Flexibel",
    },
    {
      id: 14,
      day: "Zaterdag",
      letter: "D",
      name: "Soep met broodjes",
      note: "Vaste soepdag",
    },
    { id: 15, day: "Zondag", letter: "E", name: "Nog te kiezen", note: "" },
  ],
  freezer: [
    { id: 21, name: "Bolognese", portions: 2, date: "2026-08-06" },
    { id: 22, name: "Tomatensoep", portions: 1, date: "2026-07-28" },
  ],
  hutsel: [
    { id: 31, name: "Halve paprika", days: 2 },
    { id: 32, name: "Champignons", days: 3 },
  ],
  stock: stockCatalog.map((x) => ({ ...x })),
};
const STORAGE_KEY = "gezinsplanner_data";

const RESTORE_KEY = "gezinsplanner130_restorepoint";
const RESTORE_META_KEY = "gezinsplanner130_restorepoint_meta";

function createRestorePoint() {
  try {
    persistState();
    localStorage.setItem(RESTORE_KEY, JSON.stringify(state));
    const stamp = new Date().toISOString();
    localStorage.setItem(RESTORE_META_KEY, stamp);
    updateRestoreStatus();
    alert("Herstelpunt bewaard.");
  } catch (error) {
    console.error("Herstelpunt maken mislukt:", error);
    alert("Het herstelpunt kon niet worden bewaard.");
  }
}

function restoreRestorePoint() {
  const raw = localStorage.getItem(RESTORE_KEY);
  if (!raw) {
    alert("Er is nog geen herstelpunt.");
    return;
  }
  if (
    !confirm(
      "Wil je teruggaan naar het laatst bewaarde herstelpunt? De huidige wijzigingen worden vervangen.",
    )
  )
    return;
  try {
    const restored = JSON.parse(raw);
    if (!restored || typeof restored !== "object")
      throw new Error("Ongeldig herstelpunt");
    state = restored;
    persistState();
    renderAll();
    go("start");
    updateRestoreStatus();
    alert("Herstelpunt teruggezet.");
  } catch (error) {
    console.error("Herstellen mislukt:", error);
    alert("Het herstelpunt kon niet worden teruggezet.");
  }
}

function updateRestoreStatus() {
  const el = document.getElementById("backupStatus");
  if (!el) return;
  const stamp = localStorage.getItem(RESTORE_META_KEY);
  if (!stamp) {
    el.textContent = "Nog geen herstelpunt gemaakt.";
    return;
  }
  const date = new Date(stamp);
  el.textContent = `Laatst bewaard: ${date.toLocaleDateString("nl-NL")} om ${date.toLocaleTimeString("nl-NL", { hour: "2-digit", minute: "2-digit" })}`;
}

function loadSavedState() {
  const keys = [
    STORAGE_KEY,
    "gezinsplanner132",
    "gezinsplanner131",
    "gezinsplanner130",
    "gezinsplanner129",
    "gezinsplanner128",
    "gezinsplanner127",
    "gezinsplanner126",
    "gezinsplanner125",
    "gezinsplanner124",
    "gezinsplanner122",
    "gezinsplanner121",
    "gezinsplanner120",
    "gezinsplanner119",
    "gezinsplanner118",
    "gezinsplanner117",
    "gezinsplanner116",
    "gezinsplanner115",
    "gezinsplanner114",
    "gezinsplanner113",
    "gezinsplanner112",
    "gezinsplanner111",
    "gezinsplanner110",
    "gezinsplanner19d",
    "gezinsplanner18",
    "gezinsplanner17",
    "gezinsplanner16",
    "gezinsplanner15",
    "gezinsplanner14",
    "gezinsplanner13",
    "gezinsplanner12",
    "gezinsplanner11",
    "gezinsplanner10",
  ];
  for (const key of keys) {
    const raw = localStorage.getItem(key);
    if (!raw) continue;
    try {
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === "object") return parsed;
    } catch (error) {
      console.warn("Beschadigde opslag overgeslagen:", key, error);
    }
  }
  return JSON.parse(JSON.stringify(seed));
}
let state = loadSavedState();

if (!Array.isArray(state.recipes)) state.recipes = [];
if (!Array.isArray(state.shopping)) state.shopping = [];
if (!Array.isArray(state.suppressedStockShopping)) state.suppressedStockShopping = [];

state.shopping.forEach((item) => {
  if (item.quantity === undefined) item.quantity = 1;
  if (item.weight === undefined) item.weight = "";
  if (item.weightUnit === undefined) item.weightUnit = "";
});

if (!Array.isArray(state.meals)) state.meals = [];
if (!Array.isArray(state.freezer)) state.freezer = [];
if (!Array.isArray(state.hutsel)) state.hutsel = [];
if (!Array.isArray(state.stock))
  state.stock = stockCatalog.map((x) => ({ ...x }));


defaultRecipes.forEach((recipe) => {
  const exists = state.recipes.some(
    (r) =>
      r.id === recipe.id ||
      String(r.name).trim().toLowerCase() === recipe.name.trim().toLowerCase(),
  );
  if (!exists) state.recipes.push(JSON.parse(JSON.stringify(recipe)));
});
if (!Array.isArray(state.categories)) {
  state.categories = [
    ...new Set([
      ...defaultCategories,
      ...state.stock.map((x) => x.category || "Overig"),
    ]),
  ];
}
const stockNameMap = new Map(
  state.stock.map((item) => [String(item.name).trim().toLowerCase(), item.id]),
);
const recipeStockAliases = {
  bouillontablet: "bouillonblokjes groente",
  "jong belegen kaas": "jong belegen kaas",
  "rode paprika": "paprika",
  appels: "appels",
  mayonaise: "mayonaise",
  uienpoeder: "uienpoeder",
  knoflookpoeder: "knoflookpoeder",
  kaneel: "kaneel",
  citroensap: "citroensap",
};

state.meals.forEach((meal) => {
  if (meal.recipeId) return;
  const match = state.recipes.find(
    (r) =>
      String(r.name || "")
        .trim()
        .toLowerCase() ===
      String(meal.name || "")
        .trim()
        .toLowerCase(),
  );
  if (match) meal.recipeId = match.id;
});
state.recipes.forEach((recipe) => {
  (recipe.ingredients || []).forEach((ingredient) => {
    if (ingredient.stockId) return;
    const key = String(ingredient.name || "")
      .trim()
      .toLowerCase();
    const direct = stockNameMap.get(key);
    const alias = recipeStockAliases[key]
      ? stockNameMap.get(recipeStockAliases[key])
      : null;
    ingredient.stockId = direct || alias || null;
  });
});
state.stock.forEach((x) => {
  if (!x.packageType) x.packageType = "verpakking";
  if (x.packageContent === undefined) x.packageContent = 0;
  if (!x.unit) x.unit = "gram";
  if (x.currentAmount === undefined) {
    const n = parseFloat(String(x.amount || "").replace(",", "."));
    x.currentAmount = Number.isFinite(n) ? n : 0;
  }
  if (x.minimum === undefined) x.minimum = 0;
  if (x.toHutsel === undefined) x.toHutsel = false;
  if (x.buyCount === undefined) x.buyCount = "";
  if (x.category === undefined) x.category = "Overig";
  if (!x.stockType) x.stockType = "simple";
  if (!x.simpleStatus) x.simpleStatus = "Voldoende";
});
const existingStockNames = new Set(
  state.stock.map((x) => String(x.name).trim().toLowerCase()),
);
stockCatalog.forEach((item) => {
  if (!existingStockNames.has(item.name.trim().toLowerCase()))
    state.stock.push({ ...item, id: Date.now() + item.id });
});
